In [1]:
import pandas as pd
import numpy as np
% matplotlib inline

df = pd.read_csv('noshowappointments-kagglev2-may-2016.csv')

In [2]:
df.head()

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No  
4         1           0        0             0      No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
PatientId         110527 non-null float64
AppointmentID     110527 non-null int64
Gender            110527 non-null object
ScheduledDay      110527 non-null object
AppointmentDay    110527 non-null object
Age               110527 non-null int64
Neighbourhood     110527 non-null object
Scholarship       110527 non-null int64
Hipertension      110527 non-null int64
Diabetes          110527 non-null int64
Alcoholism        110527 non-null int64
Handcap           110527 non-null int64
SMS_received      110527 non-null int64
No-show           110527 non-null object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


In [4]:
# Check the types to see if its a date
type(df['AppointmentDay'][0])

str

In [5]:
# Not a date, let's convert it to a date
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])

### Explore Data
Look at the uniques in the fields to make sure everything is ok and fix/replace values

In [6]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [7]:
df['Scholarship'].unique()

array([0, 1])

In [8]:
df['Hipertension'].unique()

array([1, 0])

In [9]:
df['Alcoholism'].unique()

array([0, 1])

In [10]:
df['Handcap'].unique()

array([0, 1, 2, 3, 4])

In [11]:
# According to https://www.kaggle.com/joniarroba/noshowappointments
# the Handcap data should only be true or false. we'll drop these
df.drop(df[df['Handcap'] > 1].index, inplace = True)
df['Handcap'].unique()

array([0, 1])

In [12]:
df['SMS_received'].unique()

array([0, 1])

In [13]:
df['Neighbourhood'].unique()

array(['JARDIM DA PENHA', 'MATA DA PRAIA', 'PONTAL DE CAMBURI',
       'REPÚBLICA', 'GOIABEIRAS', 'ANDORINHAS', 'CONQUISTA',
       'NOVA PALESTINA', 'DA PENHA', 'TABUAZEIRO', 'BENTO FERREIRA',
       'SÃO PEDRO', 'SANTA MARTHA', 'SÃO CRISTÓVÃO', 'MARUÍPE',
       'GRANDE VITÓRIA', 'SÃO BENEDITO', 'ILHA DAS CAIEIRAS',
       'SANTO ANDRÉ', 'SOLON BORGES', 'BONFIM', 'JARDIM CAMBURI',
       'MARIA ORTIZ', 'JABOUR', 'ANTÔNIO HONÓRIO', 'RESISTÊNCIA',
       'ILHA DE SANTA MARIA', 'JUCUTUQUARA', 'MONTE BELO',
       'MÁRIO CYPRESTE', 'SANTO ANTÔNIO', 'BELA VISTA', 'PRAIA DO SUÁ',
       'SANTA HELENA', 'ITARARÉ', 'INHANGUETÁ', 'UNIVERSITÁRIO',
       'SÃO JOSÉ', 'REDENÇÃO', 'SANTA CLARA', 'CENTRO', 'PARQUE MOSCOSO',
       'DO MOSCOSO', 'SANTOS DUMONT', 'CARATOÍRA', 'ARIOVALDO FAVALESSA',
       'ILHA DO FRADE', 'GURIGICA', 'JOANA D´ARC', 'CONSOLAÇÃO',
       'PRAIA DO CANTO', 'BOA VISTA', 'MORADA DE CAMBURI', 'SANTA LUÍZA',
       'SANTA LÚCIA', 'BARRO VERMELHO', 'ESTRELINHA', 'FORTE SÃO 

In [14]:
# Make it a title to be a bit more readable
df['Neighbourhood'] = df['Neighbourhood'].str.title()

In [15]:
df['Age'].unique()

array([ 62,  56,   8,  76,  23,  39,  21,  19,  30,  29,  22,  28,  54,
        15,  50,  40,  46,   4,  13,  65,  45,  51,  32,  12,  61,  38,
        79,  18,  63,  64,  85,  59,  55,  71,  49,  78,  31,  58,  27,
         6,   2,  11,   7,   0,   3,   1,  69,  68,  60,  67,  36,  10,
        35,  20,  26,  34,  33,  16,  42,   5,  47,  17,  41,  44,  37,
        24,  66,  77,  81,  70,  53,  75,  73,  52,  74,  43,  89,  57,
        14,   9,  48,  83,  72,  25,  80,  87,  88,  84,  82,  90,  86,
        91,  98,  92,  94,  96,  93,  95,  97, 102, 115, 100,  99,  -1])

In [16]:
# -1 is not an age. Have a look
df[df['Age'] == -1]

PatientId  AppointmentID Gender        ScheduledDay AppointmentDay  \
99832  4.659432e+14        5775010      F 2016-06-06 08:58:13     2016-06-06   

       Age Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
99832   -1         Romão            0             0         0           0   

       Handcap  SMS_received No-show  
99832        0             0      No

In [17]:
# Drop this row
df.drop([99832], inplace = True)

In [18]:
df['Age'].unique()

# On observation there is 0, but we assume in this case 0 is ok

array([ 62,  56,   8,  76,  23,  39,  21,  19,  30,  29,  22,  28,  54,
        15,  50,  40,  46,   4,  13,  65,  45,  51,  32,  12,  61,  38,
        79,  18,  63,  64,  85,  59,  55,  71,  49,  78,  31,  58,  27,
         6,   2,  11,   7,   0,   3,   1,  69,  68,  60,  67,  36,  10,
        35,  20,  26,  34,  33,  16,  42,   5,  47,  17,  41,  44,  37,
        24,  66,  77,  81,  70,  53,  75,  73,  52,  74,  43,  89,  57,
        14,   9,  48,  83,  72,  25,  80,  87,  88,  84,  82,  90,  86,
        91,  98,  92,  94,  96,  93,  95,  97, 102, 115, 100,  99])

In [19]:
df['Diabetes'].unique()

array([0, 1])

In [20]:
# Find the total dupes
df.duplicated().sum()

0

In [21]:
df['AppointmentID'].duplicated().sum()

0

In [22]:
# Exponentials are hard to read, lets change it to an int
df['PatientId'] = df['PatientId'].astype(int)

In [23]:
df.head()

PatientId  AppointmentID Gender        ScheduledDay AppointmentDay  \
0   29872499824296        5642903      F 2016-04-29 18:38:08     2016-04-29   
1  558997776694438        5642503      M 2016-04-29 16:08:27     2016-04-29   
2    4262962299951        5642549      F 2016-04-29 16:19:04     2016-04-29   
3     867951213174        5642828      F 2016-04-29 17:29:31     2016-04-29   
4    8841186448183        5642494      F 2016-04-29 16:07:23     2016-04-29   

   Age      Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
0   62    Jardim Da Penha            0             1         0           0   
1   56    Jardim Da Penha            0             0         0           0   
2   62      Mata Da Praia            0             0         0           0   
3    8  Pontal De Camburi            0             0         0           0   
4   56    Jardim Da Penha            0             1         1           0   

   Handcap  SMS_received No-show  
0        0             0      No  
1        0             0      No  
2        0             0      No  
3        0             0      No  
4        0             0      No

In [24]:
df.columns = df.columns.str.lower()

In [25]:
# Make columns easier to work with
df.columns = ['patient_id', 'appointment_id', 'gender', 'scheduled_day',
       'appointmentday', 'age', 'neighbourhood', 'scholarship', 'hipertension',
       'diabetes', 'alcoholism', 'handcap', 'sms_received', 'no_show']

In [26]:
# double negative of not no showing = turned up is confusing. lets rename
df['success'] = np.where(df['no_show'] == 'No', 1, 0)

In [27]:
df.drop('no_show', axis = 1, inplace = True)

In [28]:
df.head()

patient_id  appointment_id gender       scheduled_day appointmentday  \
0   29872499824296         5642903      F 2016-04-29 18:38:08     2016-04-29   
1  558997776694438         5642503      M 2016-04-29 16:08:27     2016-04-29   
2    4262962299951         5642549      F 2016-04-29 16:19:04     2016-04-29   
3     867951213174         5642828      F 2016-04-29 17:29:31     2016-04-29   
4    8841186448183         5642494      F 2016-04-29 16:07:23     2016-04-29   

   age      neighbourhood  scholarship  hipertension  diabetes  alcoholism  \
0   62    Jardim Da Penha            0             1         0           0   
1   56    Jardim Da Penha            0             0         0           0   
2   62      Mata Da Praia            0             0         0           0   
3    8  Pontal De Camburi            0             0         0           0   
4   56    Jardim Da Penha            0             1         1           0   

   handcap  sms_received  success  
0        0             0        1  
1        0             0        1  
2        0             0        1  
3        0             0        1  
4        0             0        1

In [30]:
df.to_csv('noshow_clean.csv', index = None)